### PR TITLE
DEP Update minimum version of aws/aws-sdk-php

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-dynamodb/issues/52

There are 3x commits here so do not squash merge

Updating the minimum version of aws/aws-sdk-php + phpunit to fix issues with the --prefer-lowest build https://github.com/emteknetnz/silverstripe-dynamodb/actions/runs/6106999747/job/16573142161

dispatch-ci was updated using module-standardiser - there's a PR for that linked in the parent issue

Requires https://github.com/silverstripe/gha-ci/pull/87 to be merged first for CI to pass

### CODE REVIEW

**Comment by ChloeSartorelli** [comment]
Do you know what was causing the incompatibility with the lower version constraint? Was it an incompatibility between that version of the library and AWS itself? Or with the version of AWS CLI we install in CI? Or with.... something else?
I'd like to understand that before approving this PR.

**Comment by emteknetnz** [comment]
I don't know

Issue was here - https://github.com/emteknetnz/silverstripe-dynamodb/actions/runs/6106999747/job/16573142161#step:12:70

From memory I just I bumped the version and it worked

**Review by GuySartorelli — APPROVED** [review]
I still don't like the idea of bumping the constraint without knowing why it needed to be bumped all-of-a-sudden - but I can't get the unit test to run locally so I'm going to have to just accept it and move on.

**Comment by ChloeSartorelli** [comment]
I've rerun the tests - MOG

**Comment by ChloeSartorelli** [comment]
CI is still red after rerunning the builds.

**Comment by emteknetnz** [comment]
Composer issues, looks like we need this PR merged first https://github.com/silverstripe/gha-generate-matrix/pull/68

**Comment by ChloeSartorelli** [comment]
Rerunning CI after the changes to matrix generation.

**Review by GuySartorelli — APPROVED** [review]
LGTM

**Pull request merged**
