### PR TITLE
SS4 compatibility

### PR DESCRIPTION
**Pull request by chillu**
More compat fixes on top of https://github.com/silverstripe-themes/silverstripe-simple/pull/48

### CODE REVIEW

**Comment by sminnee** [comment]
Test config is all out of whack - looks like you'll need to create a branch for the 3.x-compatible version.

**Comment by sminnee** [comment]
Looking at existing tags: we need a `2` branch and to alias master as 3.x-dev

**Comment by flamerohr** [comment]
looks like travis will need updating to incorporate composer's dump-autoload to get CI working

**Comment by chillu** [comment]
I've looked in the wrong repo when looking for previous SS4 fixes (simple theme). Which is why I didn't check branch constraints, thought that was already sorted heh.

Anyway, I've fixed the build setup, and converted it to the new-style travis config in the process. Also added linting, and fixed PSR-2 rules.

**Comment by chillu** [comment]
@flamerohr The tests are passing locally for me (when installing the module as the root folder). It's not building the most recent commit (latest build is ` 3517c22`, but the latest commit is `77e347d191`). There's something really weird going on there: https://github.com/silverstripe/silverstripe-dynamodb/commit/3517c227fd061067e6bfa6b62aad917d5d0e8b13

**Comment by chillu** [comment]
Fun bug: Renaming `code/model` to `code/Model` for PSR namespace compliance. Done it via `git mv model Model`, but that doesn’t work on a case insensitive file system like the ExtFS OSX default. So builds were passing on my system, but failing on Travis (which runs a case sensitive linux env)

**Comment by tractorcow** [comment]
Code looks fine, but just checking that you are intentionally not installing dev of framework.

image

Are you happy with this?

**Comment by chillu** [comment]
As discussed in Slack, I think non-core modules should build against releases and pre-releases of core modules, so yep - happy with this

**Pull request merged**
