### PR TITLE
Ensure APCu extension installed, this module requires it.

### PR DESCRIPTION
**Pull request by halkyon**

### CODE REVIEW

**Comment by dhensby** [comment]
no it doesn't?

**Comment by halkyon** [comment]
@dhensby It does: https://github.com/silverstripe/silverstripe-dynamodb/blob/master/code/model/DynamoDbSession.php#L58

**Comment by dhensby** [comment]
That's in an else block which means it's only needed if the constants aren't defined. so it's not a hard requirement and blocking an install because an option extension is going to make upgrade paths harder than necessary.

**Comment by halkyon** [comment]
I don't agree, clearly the person who got the error here could have seen that apcu wasn't installed before even executing the code: https://github.com/silverstripe/silverstripe-dynamodb/pull/20

But anyway, Travis refuses to play ball with me, so I'm probably going to leave it for now.

**Comment by dhensby** [comment]
if `AWS_ACCESS_KEY` and `AWS_SECRET_KEY` are defined (as per the readme) then `APCu` is not required and to block an install because of that is definitely excessive.

We can add it as a suggest, perhaps, or provide a more helpful error if the constants aren't defined and `ApcuCache` class doesn't exist, or both.

I definitely don't want to make upgrade paths more difficult so that some people don't get an error.

**Comment by halkyon** [comment]
I suppose we could code in a fallback to the filesystem cache as proposed in #20, if the `APCu` extension isn't installed?

**Comment by dhensby** [comment]
Sure

**Comment by halkyon** [comment]
I'll have a look at that, closing this PR :)

**Comment by dhensby** [comment]
thanks

**Pull request closed without merging**
